-- V1__create_author_table.sql
CREATE TABLE author (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        name VARCHAR(255) NOT NULL,
                        email VARCHAR(255),
                        nationality VARCHAR(100)
);

CREATE TABLE book (
                      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      isbn VARCHAR(13) NOT NULL,
                      title VARCHAR(255) NOT NULL,
                      price FLOAT NOT NULL,
                      available BOOLEAN NOT NULL,
                      author_id BIGINT NOT NULL,
                      book_type VARCHAR(50) NOT NULL,
                      genre VARCHAR(50),
                      is_series BOOLEAN,
                      subject VARCHAR(50),
                      reference_number INTEGER,
                      CONSTRAINT fk_author FOREIGN KEY (author_id) REFERENCES author(id)
);